export const base_url_img = 'https://image.tmdb.org/t/p/w200/'
export const base_url = 'https://api.themoviedb.org/3/'
export const api_key = '8cfaa9c2cd892c338c650dbcf1149226'

export const FETCH_MOVIES_START = 'FETCH_MOVIES_START'
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS'
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE'
export const FETCH_MOVIES_BY_ID_START = 'FETCH_MOVIES_BY_ID_START'
export const FETCH_MOVIES_BY_ID_SUCCESS = 'FETCH_MOVIES_BY_ID_SUCCESS'
export const FETCH_MOVIES_BY_ID_FAILURE = 'FETCH_MOVIES_BY_ID_FAILURE'
export const CLEAN_MOVIE = 'CLEAN_MOVIE'